<?php
/**
 * Created by PhpStorm.
 * User: songwenyao
 * Date: 2018/11/29
 * Time: 2:09 PM
 */
namespace App\Model\Sales\Team;

use Base\Db;
use EasySwoole\Core\Component\Logger;

class SalesKpiCCCalcModel extends SalesKpiCCModel
{
    protected $key_map = [
        'data_date'=>'日期',
        'dept'=>'部门',
        'team'=>'团队',
        'salesman'=>'姓名',
        'level'=>'职级',
        'online_time'=>'上线日期',
        'resign_time'=>'离职日期',
        'is_share'=>'是否分标',
        'share_day'=>'分标天数',
        'salary_base'=>'基本工资',
        'salary_kpi_base'=>'基本绩效工资',
        'perform_target'=>'业绩指标',
        'perform_weight'=>'业绩权重',
        'perform_actual'=>'实际业绩',
        '"" as perform_rate'=>'业绩达标率',
        '"" as salary_kpi'=>'业绩指标绩效工资',
        'trans_rate_target'=>'转化率指标',
        'trans_rate_weight'=>'转化率权重',
        'source_num'=>'资源量',
        'order_num'=>'有效订单',
        '"" as trans_rate_actual'=>'转化率实际完成',
        'trans_rate_rate'=>'转化率达标率',
        '"" as salary_trans_rate'=>'转化率绩效工资',
        'call_sec_target'=>'日均通时指标',
        'call_sec_weight'=>'日均通时权重',
        'work_day'=>'工作天数',
        'call_sec'=>'有效通时',
        '"" as call_sec_avg'=>'累计日均通时',
        '"" as call_sec_avg_rate'=>'日均通时达标率',
        '"" as salary_kpi_sec'=>'日均通时绩效工资',
        '"" as composite_rate'=>'综合达标率',
        'salary_kpi_minus'=>'绩效扣减',
        '"" as salary_kpi_actual'=>'实际绩效考核工资',
        '"" as salary_kpi_weight_total'=>'绩效权重合计', //计算
        '"" as salary_kpi_reward'=>'达标奖',
        '"" as salary_finally'=>'月工资总和',
    ];

    /*public function getKeyMap()
    {
        return $this->key_map; // TODO: Change the autogenerated stub
    }*/

    public function getSalaryData($condition, $page=1, $limit=20)
    {
        unset($this->key_map['salary_kpi_weight_total']);
        $this->key_map['business_type'] = 1;
        $this->key_map['region'] = 1;
        $this->key_map['structure_type'] = 1;
        $this->key_map['holiday_day'] = 1;
        $base_data = parent::getSalaryData($condition, $page, $limit);
        if(!empty($base_data)){
            foreach($base_data as $k=>$item){
                $item['perform_rate']= $this->calcPerform_rate($item);
                $item['salary_kpi'] = $this->calcSalary_kpi($item);
                $base_data[$k]['trans_rate_actual'] = $item['trans_rate_actual'] = $this->calcTrans_rate_actual($item);
                $item['trans_rate_rate'] = $this->calcTrans_rate_rate($item);
                $item['salary_trans_rate'] = $this->calcSalary_trans_rate($item);
                $item['call_sec_avg'] = $this->calcCall_sec_avg($item);
                $item['call_sec_avg_rate'] = $this->calcCall_sec_avg_rate($item);
                $item['salary_kpi_sec'] = $this->calcSalary_kpi_sec($item);
                $base_data[$k]['composite_rate'] = $this->calcComposite_rate($item);
                $item['salary_kpi_actual'] = $this->calcSalary_kpi_actual($item);
                $item['salary_kpi_weight_total'] = $this->calcSalary_kpi_weight_total($item);
                $item['salary_kpi_reward'] = $this->getSalary_kpi_reward($item);
                $base_data[$k]['salary_finally'] = $this->numberFormat(($item['salary_kpi_actual']+$item['salary_base']+$item['salary_kpi_reward'])-$item['salary_kpi_minus'],2);

                $base_data[$k]['perform_rate'] = $this->numberFormat($item['perform_rate'], 2);
                $base_data[$k]['salary_kpi'] = $this->numberFormat($item['salary_kpi'], 2);
                $base_data[$k]['trans_rate_actual'] = $this->numberFormat($item['trans_rate_actual'], 2);
                $base_data[$k]['trans_rate_rate'] = $this->numberFormat($item['trans_rate_rate'], 2);
                $base_data[$k]['salary_trans_rate'] = $this->numberFormat($item['salary_trans_rate'], 2);
                $base_data[$k]['call_sec_avg'] = $this->numberFormat($item['call_sec_avg'], 2);
                $base_data[$k]['call_sec_avg_rate'] = $this->numberFormat($item['call_sec_avg_rate'], 2);
                $base_data[$k]['salary_kpi_sec'] = $this->numberFormat($item['salary_kpi_sec'], 2);
                $base_data[$k]['salary_kpi_actual'] = $this->numberFormat($item['salary_kpi_actual'], 2);
                $base_data[$k]['salary_kpi_weight_total'] = $this->numberFormat($item['salary_kpi_weight_total'], 2);
                $base_data[$k]['salary_kpi_reward'] = $this->numberFormat($item['salary_kpi_reward'], 2);
                unset($base_data[$k]['business_type'],
                    $base_data[$k]['region'],
                    $base_data[$k]['structure_type'],$base_data[$k]['holiday_day']);
            }
        }
        return $base_data;
    }

}